version: "1"
services:
  #estadisticas-futbol-backend:
  #  container_name: estadisticas-futbol-backend
  #  image: dockerfile
  #  build: .
  #  ports:
  #    - "5001:5001"
  #  links:
  #    - mongo
  #  volumes:
  #    - ./:/usr/src/app/
  #estadisticas-futbol-frontend:
  #  container_name: estadisticas-futbol-frontend
  #  image: src/apps/estadisticasfutbol/frontend/dockerfile
  #  build: ./src/apps/estadisticasfutbol/frontend
  #  ports:
  #    - "3000:3000"
  #  depends_on:
  #    estadisticas-futbol-backend:
  #      condition: service_started
  #  volumes:
  #    - ./src/apps/estadisticasfutbol/frontend:/usr/src/app/
  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - mongolo
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/
    depends_on:
      mongo:
        condition: service_started
    networks:
      - mongolo
networks:
  mongolo:
    driver: bridge
